import { defineArrayMember, defineField, defineType } from 'sanity'

const DEFAULT_DIAL_ROWS = [
  // {
  //   _type: 'dialRow',
  //   label: 'Engine Cleaner',
  //   spectrumPrefix: false,
  //   instructionLine1: 'Apply to entire engine.',
  //   instructionLine2: 'Spot free rinse.',
  //   instructionLine2Bold: true,
  //   bgColor: '#4a4a52',
  //   fgColor: '#ffffff',
  //   variant: 'default',
  // },
  {
    _type: 'dialRow',
    label: 'Tire & Wheel Cleaner',
    spectrumPrefix: true,
    instructionLine1: 'Apply to wheels or tires.',
    instructionLine2: 'High pressure rinse.',
    instructionLine2Bold: true,
    bgColor: '#ffffff',
    fgColor: '#1B4FD9',
    variant: 'default',
  },
  {
    _type: 'dialRow',
    label: 'Low Pressure Presoak',
    spectrumPrefix: true,
    instructionLine1: 'Apply to entire vehicle',
    instructionLine2: 'from bottom up.',
    instructionLine2Bold: false,
    bgColor: '#e6157a',
    fgColor: '#ffffff',
    variant: 'default',
  },
  {
    _type: 'dialRow',
    label: 'High Pressure Detergent',
    spectrumPrefix: true,
    instructionLine1: 'Apply to entire vehicle',
    instructionLine2: 'from bottom up.',
    instructionLine2Bold: false,
    bgColor: '#f08a17',
    fgColor: '#ffffff',
    variant: 'default',
  },
  {
    _type: 'dialRow',
    label: 'Foaming Brush Detergent',
    spectrumPrefix: true,
    instructionLine1: 'Scrub vehicle, top to bottom.',
    instructionLine2: 'High pressure rinse.',
    instructionLine2Bold: true,
    bgColor: '#1B4FD9',
    fgColor: '#ffffff',
    variant: 'default',
  },
  {
    _type: 'dialRow',
    label: 'High Pressure Rinse',
    spectrumPrefix: false,
    instructionLine1: 'Rinse entire vehicle',
    instructionLine2: 'from top down.',
    instructionLine2Bold: false,
    bgColor: '#FFD93D',
    fgColor: '#08183F',
    variant: 'default',
  },
  {
    _type: 'dialRow',
    label: 'Clear Coat Sealant',
    spectrumPrefix: true,
    instructionLine1: 'Apply to entire vehicle.',
    instructionLine2: 'Finish with final rinse.',
    instructionLine2Bold: true,
    bgColor: '#b8d54a',
    fgColor: '#08183F',
    variant: 'default',
  },
  {
    _type: 'dialRow',
    label: 'DuraShield Gloss',
    spectrumPrefix: false,
    instructionLine1: 'Apply to entire vehicle.',
    instructionLine2: 'Finish with final rinse.',
    instructionLine2Bold: true,
    bgColor: '#1B4FD9',
    fgColor: '#ffffff',
    variant: 'lustra',
  },
  {
    _type: 'dialRow',
    label: 'Spot Free Rinse',
    spectrumPrefix: false,
    instructionLine1: 'Apply spot free rinse',
    instructionLine2: 'to entire vehicle.',
    instructionLine2Bold: false,
    bgColor: '#3fb5e6',
    fgColor: '#ffffff',
    variant: 'default',
  },
  {
    _type: 'dialRow',
    label: 'STOP',
    spectrumPrefix: false,
    instructionLine1: 'Safety feature,',
    instructionLine2: 'time continues to run.',
    instructionLine2Bold: false,
    bgColor: '#e32a2a',
    fgColor: '#ffffff',
    variant: 'stop',
  },
]

export default defineType({
  name: 'instructions',
  title: 'Self-serve instructions',
  type: 'document',
  preview: { prepare: () => ({ title: 'Self-serve instructions' }) },
  fields: [
    defineField({ name: 'eyebrow', type: 'string', initialValue: 'Self-serve dial' }),
    defineField({ name: 'sectionNumber', type: 'string', initialValue: '05' }),
    defineField({ name: 'headlineLine1', type: 'string', initialValue: 'Ten settings.' }),
    defineField({ name: 'headlineLine2', type: 'string', initialValue: 'One **clean** car.' }),
    defineField({ name: 'tip', type: 'text', rows: 4 }),
    defineField({ name: 'priceLabel', type: 'string', description: 'e.g. "$4 / 5 min"', initialValue: '$4 / 5 min' }),
    defineField({
      name: 'dialRows',
      title: 'Dial chart rows',
      description:
        'The 10 colored arrow-rows shown to the right of the headline. Drag to reorder. Leave empty to keep the built-in default.',
      type: 'array',
      initialValue: DEFAULT_DIAL_ROWS,
      of: [
        defineArrayMember({
          type: 'object',
          name: 'dialRow',
          fields: [
            defineField({
              name: 'label',
              type: 'string',
              description: 'Setting name, e.g. "Tire & Wheel Cleaner".',
              validation: (r) => r.required(),
            }),
            defineField({
              name: 'spectrumPrefix',
              type: 'boolean',
              description: 'Prepend the "Spectrum®" mark in front of the label.',
              initialValue: false,
            }),
            defineField({
              name: 'instructionLine1',
              type: 'string',
              description: 'First line of the instruction, e.g. "Apply to entire vehicle".',
              validation: (r) => r.required(),
            }),
            defineField({
              name: 'instructionLine2',
              type: 'string',
              description: 'Optional second line.',
            }),
            defineField({
              name: 'instructionLine2Bold',
              type: 'boolean',
              description: 'Render the second line bold (used for "Spot free rinse." style callouts).',
              initialValue: true,
            }),
            defineField({
              name: 'bgColor',
              type: 'string',
              description: 'Arrow background color (hex, e.g. "#e6157a"). Ignored when variant is set.',
              initialValue: '#1B4FD9',
            }),
            defineField({
              name: 'fgColor',
              type: 'string',
              description: 'Arrow text color (hex, e.g. "#ffffff"). Ignored when variant is set.',
              initialValue: '#ffffff',
            }),
            defineField({
              name: 'variant',
              type: 'string',
              description:
                'Special styling. "lustra" renders the script DuraShield Gloss label on a purple gradient. "stop" renders the red STOP badge.',
              options: { list: ['default', 'lustra', 'stop'], layout: 'radio' },
              initialValue: 'default',
            }),
          ],
          preview: {
            select: { label: 'label', line1: 'instructionLine1', variant: 'variant' },
            prepare: ({ label, line1, variant }) => ({
              title: label || '(no label)',
              subtitle: [variant && variant !== 'default' ? `[${variant}]` : null, line1]
                .filter(Boolean)
                .join(' '),
            }),
          },
        }),
      ],
    }),
  ],
})
